### PR TITLE
Update dependencies (mostly plyr)

### PR DESCRIPTION
**Pull request by cs462-unikent**
Attempt to resolve safari crash bug + Ipad iframe video play bug

### CODE REVIEW

**Comment by eg270-unikent** [comment]
@cs462-unikent I've merged develop into this branch and rerun grunt, can you double check this hasn't removed any of your changes?

**Comment by cs462-unikent** [comment]
I think @do225-unikent s branch superseded mine. Unsure if he's put a PR in. if his has been merged, potentally this one can just be closed.

**Comment by eg270-unikent** [comment]
@cs462-unikent develop is still `"plyr": "^1.8.2",` so I think this one still needs to be merged as Dom's branch didn't have the updated package.json

**Comment by eg270-unikent** [comment]
Do not merge - need to test that @do225-unikent's fix for plyr still works with the updated version. @do225-unikent can you check locally?

**Comment by do225-unikent** [comment]
@eg270-unikent Checked locally, all working fine. Have also fixed the conflicts.

**Pull request merged**
